### PR TITLE
Set SpringBoard preference using Apple-sanctioned CF API.

### PR DESCRIPTION
**Pull request by summertriangle-dev**
This would appear to fix your outstanding iOS 8 issue.

Reddit post: https://www.reddit.com/r/TweakBounty/comments/2yydhh/100update_myvibe_to_ios_8/

Apparently the requester would like to see your comment on this change.

### CODE REVIEW

**Comment by evandcoleman** [comment]
Thanks for contributing! I'll test this out later today and get back to you.

**Comment by evandcoleman** [comment]
It doesn't appear to be working for me. If i change the vibrate settings in Settings > Sound and then place the phone on a table, wait for it to active, remove from the table, wait for it to deactivate, it will revert the vibrate settings to the originals not the changed ones.

**Comment by summertriangle-dev** [comment]
Yep, I can reproduce that. Looks like it's an issue with the preferences hook - removed the dylib and it works as intended.

**Comment by evandcoleman** [comment]
I'm out of town at the moment, so I'll test and merge (if it works) early next week. Thanks!

**Comment by evandcoleman** [comment]
Looks good! Merging. Thanks!

**Pull request merged**
